version: '3.9'

services:
  # Сервис для разворачивания контейнера с базой данных
  database:
    image: postgres:15.2
    restart: always
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=animal-chipization
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  # Сервис для разворачивания контейнера с приложением
  webapi:
    container_name: webapi
    build: ../Sources
    command: bash -c "ls && python3.11 Sources/db/models.py && uvicorn Sources.api.main:app --host 0.0.0.0 --port 8080 --reload"
    ports:
      - "8080:8080"
    depends_on:
      - database
    volumes:
      - .:/app
    restart: always
    environment:
      - POSTGRESQL_CONFIG=postgresql+psycopg2://user:password@database/animal-chipization

  # Сервис для разворачивания контейнера с автотестами
  tests:
    image: mrexpen/planet_olymp_phase1
    pull_policy: always
    ports:
      - "8090:8080"
    depends_on:
      - webapi
    environment:
      SERVER_URL: http://webapi:8080
      STAGE: all
      # all - запуск всех тестов из трёх доступных этапов
      # 0, 1 или 2 - запуск тестов для соответствующего этапа
